name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Change Into Inner Folder
      run: | 
        cd nyt_archive_search
        pwd
        ls -a
    - name: Install Secret API Key
      run: |
        api_key=${{ secrets.api_key }}
        sed -i "1s/.*/NYT_API_KEY = '$api_key'/" gatherer/config.py
    - name: Run Tests
      run: |
        python manage.py test
