name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Python Dependency Installation
      uses: py-actions/py-dependency-install@v4.0.0
      with:
          path: "nyt_archive_search/requirements.txt"
          
    - name: Chrome Installation
      uses: browser-actions/setup-chrome@v1.0.0
      with: 
          chrome-version: stable
    - run: chrome --version 
    
    - name: Change Into Inner Folder
      run: | 
        cd nyt_archive_search
        pwd
        ls -a
    - name: Install Secret API Key
      run: |
        api_key=${{ secrets.api_key }}
        sed -i "1s/.*/NYT_API_KEY = '$api_key'/" nyt_archive_search/gatherer/config.py
    - name: Run Tests
      run: |
        pwd 
        ls -a
        cd nyt_archive_search
        pwd
        ls -a
        python manage.py test
